import { Deal, LocationZone, Post, Testimonial } from "./types";

export const DEALS: Deal[] = [
  {
    slug: "premium-residential-plot-new-chandigarh",
    title: "Premium Residential Plot Opportunity",
    subtitle: "Planned township belt with long-horizon upside",
    city: "new-chandigarh",
    cityLabel: "New Chandigarh",
    microLocation: "Eco City Extension Belt, near Madhya Marg extension",
    type: "Residential Plot",
    purpose: ["investment", "self-use"],
    status: "Fresh Inventory",
    badges: ["Undervalued", "Premium Plot", "NRI Friendly"],
    price: 9800000,
    priceMax: 21500000,
    pricePerUnit: 65500,
    unit: "sq yd",
    benchmarkPerUnit: 74000,
    sizes: ["150 sq yd", "200 sq yd", "250 sq yd", "328 sq yd"],
    areaLabel: "150–328 sq yd",
    facing: "East / North-East options",
    roadWidth: "40–60 ft internal roads",
    possession: "Immediate registry possible",
    approval: "GMADA-approved plotted development",
    score: 88,
    upsideNote: "~11% below nearby comparable plotted supply",
    highlights: [
      "GMADA-planned sector grid",
      "10 mins from Madhya Marg extension",
      "Limited plotted release in this pocket",
    ],
    whyStandsOut: [
      "Asking price sits below recent transactions in adjacent pockets",
      "Planned-city street grid with wide sector roads and green belts",
      "Institutional and healthcare anchors already operational nearby",
      "Low plotted supply remaining in the immediate belt",
    ],
    locationAdvantages: [
      { label: "Chandigarh city centre", value: "20–25 mins" },
      { label: "PGI / Panjab University belt", value: "15 mins" },
      { label: "Airport", value: "45 mins" },
      { label: "Schools", value: "3 reputed schools within 10 mins" },
      { label: "Healthcare", value: "Multi-speciality hospital operational" },
    ],
    demandDrivers: [
      "Planned-city expansion catchment of Chandigarh",
      "Premium end-user pull from professionals and NRIs",
      "Constrained new plotted supply in approved pockets",
    ],
    suitsWho: ["Long-term investor", "NRI buyer", "Self-construction buyer"],
    overview:
      "Positioned in New Chandigarh's planned expansion belt, this plotted opportunity combines a below-benchmark entry with the long-term structure of a master-planned zone. Suitable for buyers weighing both self-construction and medium-to-long-term appreciation.",
    bookingAmount: 500000,
    featured: true,
    investorPick: true,
    mapX: 28,
    mapY: 22,
    hue: 152,
    faqs: [
      { q: "Is this project approved?", a: "Yes — the development sits within a GMADA-approved plotted layout. Document verification support is provided during evaluation." },
      { q: "Is a site visit available?", a: "Yes, assisted site visits run through the week. Book a slot and the team coordinates the schedule." },
      { q: "Are corner / park-facing options available?", a: "A small number of corner and green-facing plots remain; these carry a preferential-location charge." },
      { q: "Is loan assistance available?", a: "Yes, plot-purchase loan assistance is available through partner banks for eligible buyers." },
    ],
  },
  {
    slug: "growth-corridor-plot-cluster-kharar",
    title: "Growth-Corridor Plot Cluster",
    subtitle: "Value entry on the Kharar–Kurali expansion axis",
    city: "kharar",
    cityLabel: "Kharar",
    microLocation: "NH-05 side pocket, Kharar–Kurali corridor",
    type: "Township Plot",
    purpose: ["investment"],
    status: "Fresh Inventory",
    badges: ["Growth Corridor", "Early Entry", "Undervalued"],
    price: 3200000,
    priceMax: 6400000,
    pricePerUnit: 31000,
    unit: "sq yd",
    benchmarkPerUnit: 36500,
    sizes: ["100 sq yd", "125 sq yd", "150 sq yd", "200 sq yd"],
    areaLabel: "100–200 sq yd",
    facing: "Multiple facings",
    roadWidth: "30–40 ft internal roads",
    possession: "Registry-ready",
    approval: "Approved plotted colony",
    score: 81,
    upsideNote: "~15% below corridor benchmark pricing",
    highlights: [
      "Direct NH-05 corridor exposure",
      "Early-stage township pricing",
      "Strong affordability-led demand",
    ],
    whyStandsOut: [
      "Entry pricing meaningfully below the corridor's active benchmark",
      "Sits on the natural expansion path from Kharar toward Kurali",
      "Affordability band with the widest buyer pool in Tricity",
      "Developer carrying unsold inventory — negotiation headroom",
    ],
    locationAdvantages: [
      { label: "Kharar bus stand", value: "12 mins" },
      { label: "Chandigarh boundary", value: "25 mins" },
      { label: "Proposed corridor upgrades", value: "Widening announced" },
      { label: "Colleges", value: "2 university campuses within 15 mins" },
    ],
    demandDrivers: [
      "Affordability spillover from Mohali and Chandigarh",
      "Highway-led connectivity improvements",
      "Rental demand from nearby university belts",
    ],
    suitsWho: ["First plot buyer", "Long-term investor", "Value seeker"],
    overview:
      "A value-band plotted cluster on the Kharar–Kurali growth axis. The pocket is early in its maturity curve, which keeps entry pricing low while corridor upgrades and university-belt demand build the medium-term case.",
    bookingAmount: 200000,
    featured: true,
    hot: true,
    mapX: 18,
    mapY: 46,
    hue: 38,
    faqs: [
      { q: "Is this project approved?", a: "Yes, the colony holds plotted-development approval. Papers are shared during evaluation." },
      { q: "What is the booking process?", a: "Shortlist a plot, place the token booking amount, and complete registry within the agreed window." },
      { q: "Is a site visit available?", a: "Yes — weekend group visits and weekday individual visits are both available." },
    ],
  },
  {
    slug: "commercial-pocket-deal-zirakpur",
    title: "Commercial Pocket Deal",
    subtitle: "High-traffic belt frontage on the Ambala–Chandigarh axis",
    city: "zirakpur",
    cityLabel: "Zirakpur",
    microLocation: "Patiala Road high-traffic belt",
    type: "SCO / Booth",
    purpose: ["commercial", "investment"],
    status: "Ready",
    badges: ["Commercial Opportunity", "High Visibility", "Hot Zone"],
    price: 14500000,
    pricePerUnit: 12800,
    unit: "sq ft",
    benchmarkPerUnit: 14200,
    sizes: ["SCO 1,135 sq ft", "Booth 460 sq ft"],
    areaLabel: "460–1,135 sq ft",
    facing: "Main-road frontage",
    roadWidth: "200 ft arterial frontage",
    possession: "Ready — leasing possible immediately",
    approval: "Change of land use in place",
    score: 84,
    upsideNote: "Frontage priced below recent belt transactions",
    highlights: [
      "200 ft arterial frontage",
      "Dense residential catchment behind",
      "Immediate leasing potential",
    ],
    whyStandsOut: [
      "Frontage on one of Tricity's highest-footfall approach corridors",
      "Mature residential catchment feeding daily commercial demand",
      "Ready asset — rental yield can begin immediately",
      "Below-benchmark psf against recent belt transactions",
    ],
    locationAdvantages: [
      { label: "Airport", value: "15 mins" },
      { label: "Chandigarh boundary", value: "10 mins" },
      { label: "Catchment", value: "40+ residential societies within 3 km" },
      { label: "Anchor retail", value: "Two operational malls within 5 mins" },
    ],
    demandDrivers: [
      "Highest residential density growth in Tricity",
      "Transit footfall on the Ambala–Chandigarh axis",
      "F&B and daily-needs retail expansion",
    ],
    suitsWho: ["Commercial buyer", "Yield-focused investor", "Business owner"],
    overview:
      "A ready commercial asset with genuine arterial frontage in Zirakpur's highest-velocity belt. The combination of transit visibility and a dense residential catchment supports both owner-operation and leasing strategies.",
    bookingAmount: 1000000,
    featured: true,
    hot: true,
    investorPick: true,
    mapX: 58,
    mapY: 72,
    hue: 210,
    faqs: [
      { q: "Is leasing assistance available?", a: "Yes — the team can connect owners with active retail and F&B leasing demand in the belt." },
      { q: "What is the expected rental range?", a: "Comparable frontage units in the belt currently lease in a healthy range; a current rent sheet is shared on request." },
      { q: "Is a site visit available?", a: "Yes, visits are available all week including evenings to observe peak footfall." },
    ],
  },
  {
    slug: "early-stage-township-entry-mohali",
    title: "Early-Stage Township Entry",
    subtitle: "Sector-grade township in the Mohali expansion zone",
    city: "mohali",
    cityLabel: "Mohali",
    microLocation: "Sector 115–116 expansion axis, near Aerocity influence zone",
    type: "Township Plot",
    purpose: ["investment", "self-use"],
    status: "Pre-Launch",
    badges: ["Pre-Launch", "Investor Pick", "Growth Corridor"],
    price: 6900000,
    priceMax: 13800000,
    pricePerUnit: 46000,
    unit: "sq yd",
    benchmarkPerUnit: 52000,
    sizes: ["150 sq yd", "200 sq yd", "300 sq yd"],
    areaLabel: "150–300 sq yd",
    facing: "Layout allotment stage",
    roadWidth: "40–80 ft sector roads",
    possession: "Development possession in 18–24 months",
    approval: "License granted; RERA registration in process",
    score: 86,
    upsideNote: "Pre-launch pricing ~12% under sector benchmark",
    highlights: [
      "Pre-launch entry pricing",
      "Aerocity influence zone",
      "Reputed developer track record",
    ],
    whyStandsOut: [
      "Pre-launch window prices the entry below the sector's active benchmark",
      "Sits inside the Aerocity–IT City influence zone driving jobs-led demand",
      "Developer has delivered two prior plotted phases on schedule",
      "Sector-road connectivity already laid on two sides",
    ],
    locationAdvantages: [
      { label: "Airport", value: "12 mins" },
      { label: "IT City belt", value: "10 mins" },
      { label: "Mohali railway station", value: "18 mins" },
      { label: "International cricket stadium belt", value: "15 mins" },
    ],
    demandDrivers: [
      "Employment growth in IT City and Aerocity",
      "Airport-belt infrastructure investment",
      "Township-scale planning with civic amenities",
    ],
    suitsWho: ["Long-term investor", "First plot buyer", "NRI buyer"],
    overview:
      "An early-entry window into a sector-grade township on Mohali's expansion axis. Pre-launch pricing, an operating jobs corridor nearby, and a developer with delivered phases make this a structured way to buy ahead of the sector's maturity curve.",
    bookingAmount: 350000,
    featured: true,
    newListing: true,
    investorPick: true,
    mapX: 38,
    mapY: 55,
    hue: 96,
    faqs: [
      { q: "Is this RERA registered?", a: "The license is granted and RERA registration is in process; allotments are structured accordingly. Documentation status is shared transparently." },
      { q: "What is the payment plan?", a: "A construction-linked plan is available: booking amount, allotment instalment, and development-linked tranches." },
      { q: "When is possession?", a: "Development possession is targeted within 18–24 months of launch." },
    ],
  },
  {
    slug: "premium-sector-plot-panchkula",
    title: "Premium Sector Plot",
    subtitle: "Established residential sector with stable end-user pull",
    city: "panchkula",
    cityLabel: "Panchkula",
    microLocation: "Sector 27–28 established belt",
    type: "Residential Plot",
    purpose: ["self-use", "investment"],
    status: "Resale",
    badges: ["Premium Plot", "Limited Inventory"],
    price: 18500000,
    pricePerUnit: 92500,
    unit: "sq yd",
    benchmarkPerUnit: 98000,
    sizes: ["200 sq yd"],
    areaLabel: "200 sq yd",
    facing: "Park-facing, North-East",
    roadWidth: "40 ft sector road",
    possession: "Immediate",
    approval: "HSVP allotted, clear title",
    score: 79,
    upsideNote: "Motivated seller — priced under sector average",
    highlights: [
      "Park-facing corner position",
      "Fully developed sector",
      "Clear-title HSVP plot",
    ],
    whyStandsOut: [
      "Park-facing plots rarely surface in this sector",
      "Seller urgency has priced it under the sector's running average",
      "Fully built-out civic infrastructure — construct immediately",
      "Strong resale depth in established Panchkula sectors",
    ],
    locationAdvantages: [
      { label: "Chandigarh boundary", value: "8 mins" },
      { label: "Schools", value: "Top schools within the sector belt" },
      { label: "Healthcare", value: "Major hospitals within 10 mins" },
      { label: "Shivalik view", value: "Open aspect toward the foothills" },
    ],
    demandDrivers: [
      "Established end-user demand and low vacancy",
      "Scarcity of park-facing resale plots",
      "Stable premium-sector price behaviour",
    ],
    suitsWho: ["Self-construction buyer", "Premium end-user", "Wealth parker"],
    overview:
      "A rare park-facing resale plot in an established Panchkula sector, surfaced through seller urgency rather than market weakness. Best suited to buyers who value settled infrastructure and stability over speculative upside.",
    mapX: 72,
    mapY: 30,
    hue: 268,
    faqs: [
      { q: "Is the title clear?", a: "Yes — HSVP allotment with a clean chain of ownership; documents are available for legal review." },
      { q: "Can construction start immediately?", a: "Yes, the sector is fully developed and building plan approval is a standard process." },
    ],
  },
  {
    slug: "it-city-adjacent-commercial-plot-mohali",
    title: "IT City-Adjacent Commercial Plot",
    subtitle: "Commercial land beside Mohali's jobs corridor",
    city: "mohali",
    cityLabel: "Mohali",
    microLocation: "IT City adjacency, Sector 82 alpha belt",
    type: "Commercial Plot",
    purpose: ["commercial", "investment"],
    status: "Fresh Inventory",
    badges: ["Commercial Opportunity", "Investor Pick", "Growth Corridor"],
    price: 32000000,
    pricePerUnit: 128000,
    unit: "sq yd",
    benchmarkPerUnit: 141000,
    sizes: ["250 sq yd"],
    areaLabel: "250 sq yd",
    facing: "Dual access",
    roadWidth: "60 ft + 24 ft service lane",
    possession: "Immediate",
    approval: "GMADA commercial allotment",
    score: 83,
    upsideNote: "~9% under recent corridor commercial transactions",
    highlights: [
      "Beside operating IT campuses",
      "Dual road access",
      "Daytime workforce catchment",
    ],
    whyStandsOut: [
      "Directly adjacent to an operating employment corridor",
      "Commercial land in this belt trades thinly — supply is structurally limited",
      "Dual access suits retail, clinic, or office-build strategies",
      "Priced under the corridor's recent commercial transactions",
    ],
    locationAdvantages: [
      { label: "IT City campuses", value: "Walking distance" },
      { label: "Airport", value: "10 mins" },
      { label: "Residential catchment", value: "Sector 82–88 belt" },
    ],
    demandDrivers: [
      "Workforce expansion in IT City",
      "Under-served daily-needs retail in the belt",
      "Airport-road commercial gravity",
    ],
    suitsWho: ["Commercial buyer", "Developer", "Yield-focused investor"],
    overview:
      "Commercial land with dual access beside Mohali's principal jobs corridor. The daytime workforce catchment is already operating, while commercial supply in the belt remains structurally thin.",
    mapX: 42,
    mapY: 62,
    hue: 12,
    faqs: [
      { q: "What can be built here?", a: "Retail, office, or mixed commercial use as per GMADA commercial zoning; FAR details are shared during evaluation." },
      { q: "Is this leasehold or freehold?", a: "GMADA commercial allotment; conversion and transfer norms are explained during documentation review." },
    ],
  },
  {
    slug: "airport-belt-land-parcel-derabassi",
    title: "Airport-Belt Land Parcel",
    subtitle: "Strategic acreage in the logistics influence zone",
    city: "derabassi",
    cityLabel: "Derabassi Belt",
    microLocation: "Airport–Derabassi influence zone, off Ambala highway",
    type: "Land Parcel",
    purpose: ["investment"],
    status: "Fresh Inventory",
    badges: ["Early Entry", "Growth Corridor", "Undervalued"],
    price: 26000000,
    pricePerUnit: 6500,
    unit: "sq yd",
    benchmarkPerUnit: 8200,
    sizes: ["1 acre", "2 acre", "4 acre contiguous"],
    areaLabel: "1–4 acres",
    roadWidth: "Approach from 100 ft highway spur",
    possession: "Immediate",
    approval: "Agricultural title; CLU-potential zone",
    score: 76,
    upsideNote: "~20% under influence-zone benchmark",
    highlights: [
      "Logistics + industrial influence zone",
      "Contiguous acreage available",
      "Deep value entry pricing",
    ],
    whyStandsOut: [
      "Entry pricing deeply below the influence-zone benchmark",
      "Sits between the airport belt and Derabassi's industrial cluster",
      "Contiguous parcels allow scale strategies rarely available in Tricity",
      "Long-horizon land-banking profile with multiple exit paths",
    ],
    locationAdvantages: [
      { label: "Airport", value: "20 mins" },
      { label: "Ambala–Chandigarh highway", value: "5 mins" },
      { label: "Industrial cluster", value: "Derabassi belt operational" },
    ],
    demandDrivers: [
      "Airport-belt logistics expansion",
      "Industrial land absorption in Derabassi",
      "Highway-led connectivity",
    ],
    suitsWho: ["Land banker", "Institutional buyer", "Patient long-term investor"],
    overview:
      "Strategic acreage in the airport–Derabassi influence zone at a deep-value entry. This is a patient-capital position: agricultural title today, with the zone's logistics and industrial gravity building the long-term case.",
    mapX: 74,
    mapY: 86,
    hue: 200,
    faqs: [
      { q: "What is the current land use?", a: "Agricultural title. The zone has CLU precedent; any change-of-use pursuit is the buyer's independent decision." },
      { q: "Can smaller portions be bought?", a: "The minimum transaction is 1 acre; contiguous combinations up to 4 acres are available." },
    ],
  },
  {
    slug: "high-street-retail-booth-zirakpur",
    title: "High-Street Retail Booth",
    subtitle: "Compact yield asset in an operating market",
    city: "zirakpur",
    cityLabel: "Zirakpur",
    microLocation: "VIP Road retail spine",
    type: "SCO / Booth",
    purpose: ["commercial", "investment"],
    status: "Resale",
    badges: ["Commercial Opportunity", "New Listing", "High Visibility"],
    price: 5800000,
    pricePerUnit: 12600,
    unit: "sq ft",
    benchmarkPerUnit: 13800,
    sizes: ["Booth 460 sq ft"],
    areaLabel: "460 sq ft",
    facing: "Market-facing",
    possession: "Ready, tenant in place",
    approval: "Approved market complex",
    score: 74,
    upsideNote: "Tenanted asset priced under belt average",
    highlights: [
      "Tenant already in place",
      "VIP Road retail spine",
      "Low-ticket commercial entry",
    ],
    whyStandsOut: [
      "Running tenancy means yield begins on day one",
      "VIP Road catchment continues to densify",
      "Lowest-ticket commercial entry currently live on the platform",
    ],
    locationAdvantages: [
      { label: "VIP Road societies", value: "25+ societies in 2 km" },
      { label: "Chandigarh boundary", value: "8 mins" },
      { label: "Airport", value: "18 mins" },
    ],
    demandDrivers: [
      "Residential densification along VIP Road",
      "Daily-needs retail demand",
    ],
    suitsWho: ["First-time commercial buyer", "Yield seeker"],
    overview:
      "A compact, tenanted retail booth on Zirakpur's VIP Road spine — a low-ticket way to hold yielding commercial property in one of Tricity's fastest-densifying catchments.",
    newListing: true,
    mapX: 55,
    mapY: 68,
    hue: 330,
    faqs: [
      { q: "What is the current rent?", a: "The running tenancy details and rent sheet are shared after an initial consultation." },
      { q: "Is the tenancy transferable?", a: "Yes, the lease transfers with the sale as per its registered terms." },
    ],
  },
  {
    slug: "boutique-floor-plots-chandigarh-periphery",
    title: "Boutique Floor-Plot Offering",
    subtitle: "Low-density premium living on the Chandigarh periphery",
    city: "chandigarh",
    cityLabel: "Chandigarh Periphery",
    microLocation: "Southern sectors periphery belt",
    type: "Residential Unit",
    purpose: ["self-use", "investment"],
    status: "Ready",
    badges: ["Premium Plot", "Limited Inventory", "NRI Friendly"],
    price: 24500000,
    pricePerUnit: 11800,
    unit: "sq ft",
    benchmarkPerUnit: 12900,
    sizes: ["3BHK independent floor, 2,075 sq ft"],
    areaLabel: "2,075 sq ft",
    facing: "Green-belt facing",
    possession: "Ready to move",
    approval: "Approved building plans, OC received",
    score: 77,
    upsideNote: "Ready premium stock under periphery benchmark",
    highlights: [
      "OC-received, ready to move",
      "Green-belt facing",
      "Chandigarh-grade civic quality",
    ],
    whyStandsOut: [
      "Ready, compliance-complete premium stock is scarce on the periphery",
      "Green-facing aspect with low-density planning",
      "Chandigarh-adjacent address at a periphery price point",
    ],
    locationAdvantages: [
      { label: "Chandigarh sectors", value: "5–10 mins" },
      { label: "Airport", value: "20 mins" },
      { label: "Schools & healthcare", value: "City-grade options nearby" },
    ],
    demandDrivers: [
      "Spill-over demand from Chandigarh's fixed supply",
      "Premium end-user preference for low-density formats",
    ],
    suitsWho: ["Premium end-user", "NRI buyer", "Rental-yield investor"],
    overview:
      "A boutique independent-floor offering on Chandigarh's southern periphery — city-grade living, compliance complete, and priced under the periphery's premium benchmark.",
    mapX: 55,
    mapY: 42,
    hue: 45,
    faqs: [
      { q: "Is the occupation certificate received?", a: "Yes, OC is in place and the unit is ready for immediate move-in or leasing." },
      { q: "Is this freehold?", a: "Yes, freehold title with registered conveyance." },
    ],
  },
];

export const LOCATIONS: LocationZone[] = [
  {
    slug: "chandigarh",
    name: "Chandigarh",
    tagline: "Premium, mature, limited supply",
    overview:
      "The anchor of Tricity: planned sectors, fixed supply, and the region's deepest end-user demand. Opportunity here is scarce by design — which is exactly what protects value.",
    maturity: "Mature",
    growthScore: 72,
    priceBand: "₹1.2L – ₹2.5L / sq yd",
    avgPerSqYd: "₹1.6L",
    idealBuyer: ["Premium end-user", "Wealth parker", "Legacy buyer"],
    whyBuy: [
      "Fixed sector supply with enduring demand",
      "Best-in-region civic infrastructure",
      "Deep, liquid resale market",
    ],
    connectivity: [
      { label: "Airport", value: "25 mins" },
      { label: "Railway station", value: "In-city" },
      { label: "Delhi (NH-44)", value: "4 hrs" },
    ],
    trend: [100, 104, 107, 112, 118, 121, 127],
    mapX: 55,
    mapY: 35,
    hue: 45,
  },
  {
    slug: "mohali",
    name: "Mohali",
    tagline: "Infrastructure-driven growth engine",
    overview:
      "Tricity's most active growth story — IT City, Aerocity, the airport belt, and sector-grade townships are pulling jobs and residents into a structured expansion grid.",
    maturity: "Growing",
    growthScore: 91,
    priceBand: "₹40K – ₹1.3L / sq yd",
    avgPerSqYd: "₹58K",
    idealBuyer: ["Growth investor", "First plot buyer", "Commercial buyer"],
    whyBuy: [
      "Jobs-led demand from IT City and Aerocity",
      "Airport-belt infrastructure investment",
      "Widest spread of plotted and commercial formats",
    ],
    connectivity: [
      { label: "Airport", value: "In-district" },
      { label: "Chandigarh", value: "10–20 mins" },
      { label: "IT City", value: "Operational" },
    ],
    trend: [100, 108, 115, 124, 138, 149, 163],
    mapX: 40,
    mapY: 55,
    hue: 96,
  },
  {
    slug: "panchkula",
    name: "Panchkula",
    tagline: "Established premium residential appeal",
    overview:
      "Settled sectors against the Shivalik foothills with stable end-user pull. A market of quiet strength: low volatility, scarce park-facing stock, and durable premium demand.",
    maturity: "Mature",
    growthScore: 68,
    priceBand: "₹70K – ₹1.4L / sq yd",
    avgPerSqYd: "₹95K",
    idealBuyer: ["Premium end-user", "Self-construction buyer", "Stability seeker"],
    whyBuy: [
      "Established civic infrastructure",
      "Stable premium-sector pricing",
      "Foothill environment with city access",
    ],
    connectivity: [
      { label: "Chandigarh", value: "8–15 mins" },
      { label: "Shimla highway", value: "Direct" },
      { label: "Airport", value: "35 mins" },
    ],
    trend: [100, 103, 106, 110, 114, 117, 121],
    mapX: 72,
    mapY: 28,
    hue: 268,
  },
  {
    slug: "zirakpur",
    name: "Zirakpur",
    tagline: "Volume, velocity and connectivity",
    overview:
      "Tricity's highest-velocity market at the junction of three highways and the airport road. Broad price range, active inventory movement, and the region's strongest retail catchment growth.",
    maturity: "Growing",
    growthScore: 85,
    priceBand: "₹35K – ₹90K / sq yd",
    avgPerSqYd: "₹52K",
    idealBuyer: ["Commercial buyer", "Yield investor", "Connectivity-first buyer"],
    whyBuy: [
      "Junction of Ambala, Patiala and Shimla axes",
      "15 minutes from the airport",
      "Fastest residential densification in Tricity",
    ],
    connectivity: [
      { label: "Airport", value: "15 mins" },
      { label: "Chandigarh", value: "10 mins" },
      { label: "Delhi (NH-44)", value: "3.5 hrs" },
    ],
    trend: [100, 107, 113, 121, 130, 141, 150],
    mapX: 58,
    mapY: 70,
    hue: 210,
  },
  {
    slug: "new-chandigarh",
    name: "New Chandigarh",
    tagline: "Planned growth, long-term upside",
    overview:
      "A master-planned extension of the Chandigarh idea — wide sector grids, institutional anchors, and township-led plotted development still early in its maturity curve.",
    maturity: "Emerging",
    growthScore: 88,
    priceBand: "₹45K – ₹85K / sq yd",
    avgPerSqYd: "₹62K",
    idealBuyer: ["Long-term investor", "NRI buyer", "Premium self-builder"],
    whyBuy: [
      "GMADA master-planned sector structure",
      "Healthcare and education anchors operational",
      "Early position in a planned-city trajectory",
    ],
    connectivity: [
      { label: "Chandigarh", value: "20 mins" },
      { label: "PGI belt", value: "15 mins" },
      { label: "Airport", value: "45 mins" },
    ],
    trend: [100, 109, 117, 128, 141, 152, 168],
    mapX: 30,
    mapY: 20,
    hue: 152,
  },
  {
    slug: "kharar",
    name: "Kharar",
    tagline: "Affordability with a future-appreciation play",
    overview:
      "Tricity's value frontier. The widest affordability band in the region, university-belt rental demand, and corridor upgrades that keep pulling the growth line westward.",
    maturity: "Emerging",
    growthScore: 82,
    priceBand: "₹22K – ₹45K / sq yd",
    avgPerSqYd: "₹31K",
    idealBuyer: ["First plot buyer", "Value investor", "Rental-yield seeker"],
    whyBuy: [
      "Lowest meaningful entry point in Tricity",
      "University-belt rental demand",
      "Corridor upgrades underway toward Kurali",
    ],
    connectivity: [
      { label: "Mohali", value: "15 mins" },
      { label: "Chandigarh", value: "25 mins" },
      { label: "Kurali corridor", value: "Widening announced" },
    ],
    trend: [100, 106, 114, 123, 134, 147, 158],
    mapX: 20,
    mapY: 45,
    hue: 38,
  },
  {
    slug: "derabassi",
    name: "Derabassi & Airport Belt",
    tagline: "Emerging logistics and industrial influence",
    overview:
      "The region's strategic frontier — logistics parks, industrial absorption, and airport-belt gravity are re-pricing land along the Ambala axis. A patient-capital market.",
    maturity: "Emerging",
    growthScore: 78,
    priceBand: "₹5K – ₹20K / sq yd",
    avgPerSqYd: "₹9K",
    idealBuyer: ["Land banker", "Institutional buyer", "Patient investor"],
    whyBuy: [
      "Deepest value pricing in the region",
      "Industrial and logistics absorption",
      "Airport influence zone",
    ],
    connectivity: [
      { label: "Airport", value: "20 mins" },
      { label: "Ambala highway", value: "Direct" },
      { label: "Zirakpur", value: "15 mins" },
    ],
    trend: [100, 105, 112, 120, 131, 140, 154],
    mapX: 74,
    mapY: 84,
    hue: 200,
  },
];

export const POSTS: Post[] = [
  {
    slug: "best-areas-to-buy-plot-in-tricity",
    title: "Best Areas to Buy a Plot in Tricity in 2026",
    category: "Area Guides",
    excerpt:
      "From New Chandigarh's planned grids to Kharar's value frontier — a structured look at where plotted demand is actually moving, and why.",
    date: "2026-06-28",
    readMins: 8,
    body: [
      "Tricity's plotted market is not one market — it is at least six, each with its own price logic, buyer profile, and maturity curve. Treating them as interchangeable is the most common mistake first-time plot buyers make.",
      "New Chandigarh offers the cleanest long-horizon story: GMADA master planning, operational institutional anchors, and constrained approved supply. Entry pricing is no longer cheap, but the structure of the market protects it.",
      "Mohali is the jobs story. IT City and the Aerocity belt are converting employment growth into plotted demand faster than any other pocket in the region. Sector-grade townships on the expansion axis are the natural expression of that demand.",
      "Kharar and the Kurali corridor remain the value frontier. Pricing is the lowest meaningful entry in Tricity, and corridor upgrades keep pulling the growth line westward. The trade-off is maturity: buyers here need patience and careful project selection.",
      "Zirakpur is a connectivity play more than a plotted play — its strength is velocity and catchment density, which favours commercial formats over pure land holding.",
      "The right answer depends on your horizon: end-users should weight civic maturity, while appreciation-focused buyers should weight corridor exposure and entry price against benchmark.",
    ],
  },
  {
    slug: "new-chandigarh-vs-mohali-long-term",
    title: "New Chandigarh vs Mohali: Where Is the Better Long-Term Play?",
    category: "Comparisons",
    excerpt:
      "Two growth stories, two different engines — planning-led scarcity versus jobs-led demand. How to choose between Tricity's leading long-term markets.",
    date: "2026-06-14",
    readMins: 9,
    body: [
      "New Chandigarh and Mohali dominate every long-term conversation about Tricity real estate — but they appreciate for different reasons, and that difference should drive your choice.",
      "New Chandigarh's engine is planning-led scarcity. GMADA's master plan fixes the shape of supply, and approved plotted pockets are finite. When demand grows against fixed supply, price follows structurally.",
      "Mohali's engine is jobs-led demand. IT City, Aerocity and the airport belt keep adding employment, and employment converts into housing demand within a commute radius. Its supply is larger, but so is its absorption.",
      "For a 10-year-plus horizon with minimal management, New Chandigarh's structure is hard to beat. For a 5–8 year horizon with more liquidity and rental optionality, Mohali's depth wins.",
      "Many of the strongest Tricity portfolios simply hold both: a New Chandigarh plot as the patient anchor, and a Mohali position for velocity.",
    ],
  },
  {
    slug: "what-makes-a-property-feel-undervalued",
    title: "What Makes a Property Actually Undervalued?",
    category: "Buying Process",
    excerpt:
      "'Cheap' and 'undervalued' are not the same thing. The six signals we check before a deal earns the undervalued badge on BookAPlot.",
    date: "2026-05-30",
    readMins: 7,
    body: [
      "Every portal is full of 'cheap' listings. Very few are undervalued. The difference is whether the price gap has a reason that resolves in your favour — or a reason that never resolves at all.",
      "We start with the micro-market pricing gap: how the asking compares with recent transactions in the same pocket, not city-wide averages that hide everything useful.",
      "Then corridor exposure — is the asset on a path where infrastructure, employment, or planned development is actively moving toward it? A price gap plus an approaching corridor is a very different asset from a price gap in a static pocket.",
      "Connectivity, area maturity stage, end-use demand, and inventory quality complete the checklist. A plot nobody would actually build on is not undervalued at any price.",
      "When a deal clears these filters, the discount usually has a mundane explanation — seller urgency, unsold developer inventory, a pre-launch window. Those are the gaps worth acting on.",
    ],
  },
  {
    slug: "zirakpur-opportunity-or-oversupply",
    title: "Zirakpur Real Estate: Opportunity or Oversupply?",
    category: "Market Updates",
    excerpt:
      "The region's fastest-moving market divides opinion. A grounded look at where Zirakpur's velocity is genuine demand — and where it's just inventory.",
    date: "2026-05-12",
    readMins: 8,
    body: [
      "Zirakpur triggers stronger opinions than any other Tricity market. Sceptics see high-rise oversupply; believers see the region's best connectivity story. Both are looking at real data — just at different segments.",
      "In the apartment segment, supply has genuinely run ahead of absorption in some belts, which is where the oversupply reputation comes from.",
      "The commercial story is different. Residential densification is real and compounding — every delivered tower adds daily-needs demand, and retail supply on the key spines has not kept pace. That is why frontage assets on VIP Road and the Patiala Road belt keep re-rating.",
      "The junction position — Ambala, Patiala, Shimla axes plus the airport road — is not replicable. Connectivity-driven markets forgive many sins over time.",
      "Our read: be selective in residential, be serious about commercial frontage, and treat catchment density as the primary signal.",
    ],
  },
  {
    slug: "things-to-check-before-buying-plot-kharar",
    title: "7 Things to Check Before Buying a Plot in Kharar",
    category: "Buying Process",
    excerpt:
      "Kharar's pricing is the most accessible in Tricity — which makes disciplined verification even more important. A practical checklist.",
    date: "2026-04-25",
    readMins: 6,
    body: [
      "Kharar's affordability attracts first-time plot buyers — and first-time mistakes. The good news: a disciplined checklist removes most of the risk.",
      "First, approval status. Insist on seeing the plotted-colony approval itself, not a brochure claim. Unapproved colonies trade at tempting discounts for a reason.",
      "Second, the registry path: confirm the plot can be registered in your name immediately, not through a chain of agreements.",
      "Third, physical development — roads, drainage, and electrification on the ground, not on the layout plan. Fourth, the corridor logic: pockets on the Kurali axis behave very differently from pockets buried off-grid.",
      "Fifth, price against pocket benchmark, not against Mohali. Sixth, developer track record on earlier phases. Seventh, exit depth — how many transactions actually happen in that pocket per year.",
      "None of this is complicated. It is simply work — which is exactly why doing it puts you ahead of most of the market.",
    ],
  },
  {
    slug: "residential-vs-commercial-plot-tricity",
    title: "Residential vs Commercial Plot Investment in Tricity",
    category: "Plotted Insights",
    excerpt:
      "Two very different return engines — appreciation versus yield. How the maths, the risks, and the effort compare in the Tricity context.",
    date: "2026-04-08",
    readMins: 9,
    body: [
      "Residential plots and commercial land are often lumped together as 'property investment'. In practice they are different asset classes with different return engines.",
      "Residential plotted returns in Tricity are appreciation-led: you are underwriting the maturity curve of a pocket. Cash flow is zero (or negative, counting holding costs) until exit.",
      "Commercial returns are yield-led with an appreciation kicker. A tenanted booth or SCO produces income from day one, and the region's densification keeps repricing good frontage.",
      "The effort profile differs too: residential plots are near-zero management; commercial assets need tenancy management and belt-level judgement about catchment growth.",
      "Ticket sizes push the same way — meaningful commercial frontage in Tricity starts well above entry-level plotted pricing. For many buyers the honest answer is sequencing: plotted first for the base, commercial second for the yield.",
    ],
  },
];

export const TESTIMONIALS: Testimonial[] = [
  {
    quote:
      "The platform felt different from a normal portal. The way deals were explained made shortlisting much faster.",
    name: "Rohit S.",
    context: "Plot buyer, Mohali",
  },
  {
    quote:
      "We were able to compare multiple plotted options in Mohali and New Chandigarh without the usual confusion.",
    name: "Amanpreet & Simran K.",
    context: "First-time buyers",
  },
  {
    quote:
      "The site visit and follow-up experience felt much more structured than working through scattered listings.",
    name: "Vikram M.",
    context: "NRI investor, Canada",
  },
];

export const STATS = [
  { value: 140, suffix: "+", label: "Undervalued deals tracked" },
  { value: 22, suffix: "", label: "Micro-markets covered across Tricity" },
  { value: 3200, suffix: "+", label: "Buyer inquiries handled" },
  { value: 640, suffix: "+", label: "Site visits coordinated" },
  { value: 9, suffix: " days", label: "Avg. deal discovery lead time" },
  { value: 60, suffix: ":40", label: "Residential : commercial mix" },
];

export const dealsByCity = (city: string) => DEALS.filter((d) => d.city === city);
export const getDeal = (slug: string) => DEALS.find((d) => d.slug === slug);
export const getLocation = (slug: string) => LOCATIONS.find((l) => l.slug === slug);
export const getPost = (slug: string) => POSTS.find((p) => p.slug === slug);
